-- MySQL schemas
-- Keeping track of your MySQL schemas can help with automating adding tables
-- to your MySQL database. Simply add the table schema below and use the import
-- command to upload it to your database.

-- To import your schemas into your database, run:
-- `mysql -u <username> -p <database> < schema.sql` from the project directory
-- where <username> is your MySQL username and <database> is the MySQL
-- database of interest.

-- An Example Schema:
--  CREATE TABLE IF NOT EXISTS employees (
--    emp_no INT(11),
--    birth_date DATE,
--    first_name VARCHAR(14),
--    last_name VARCHART(16),
--    gender ENUM('M','F'),
--    hire_date DATE
--
--    PRIMARY KEY (emp_no)
--  ) ENGINE = InnoDB DEFAULT CHARSET = "utf8";
